### ISSUE TITLE
Keep references to tasks in utils.scheduling.create_task

### ISSUE THREAD

**Issue by wookie184** [python-discord/bot-core#140]
Quite a common (https://github.com/python-discord/bot/search?q=create_task) code pattern is to create a task with [`scheduling.create_task`](https://github.com/python-discord/bot-core/blob/ac156ecc63e0cd0ea54d58020efe8df3c6e39c86/botcore/utils/scheduling.py#L215-L242) and not assign the returned task to anything.

The [documentation for `create_task`](https://docs.python.org/3.10/library/asyncio-task.html#asyncio.create_task) (used under the hood by `scheduling`) warns against this:

> **Important**
> Save a reference to the result of this function, to avoid a task disappearing mid-execution. The event loop only keeps weak references to tasks. A task that isn’t referenced elsewhere may get garbage collected at any time, even before it’s done.

It's not entirely clear whether this actually effects us, from what I can tell it only actually becomes an issue under exceptional circumstances. Still, I propose we use the suggested solution and keep a set of background tasks:

> For reliable “fire-and-forget” background tasks, gather them in a collection:
> ```python
>background_tasks = set()
>
>for i in range(10):
>    task = asyncio.create_task(some_coro(param=i))
>
>    # Add task to the set. This creates a strong reference.
>    background_tasks.add(task)
>
>    # To prevent keeping references to finished tasks forever,
>    # make each task remove its own reference from the set after
>    # completion:
>    task.add_done_callback(background_tasks.discard)
>```

**Comment by shtlrs** [comment]
So the only thing that needs to be done here is to keep reference of all tasks that are created by `asyncio.create_task` ?

**Comment by ChrisLovering** [comment]
We already do this don't we?

https://github.com/python-discord/bot-core/blob/main/pydis_core/utils/scheduling.py#L80

I believe it was mostly added so that The below dunder works, but it should also alleviate the above issue.
https://github.com/python-discord/bot-core/blob/main/pydis_core/utils/scheduling.py#L44

**Comment by shtlrs** [comment]
@wookie184 What do you think of creating a global `TASKS` inside the `scheduling` module and save those tasks there ?
We would of course add a callback to clear it from the set once done along with the `_log_task_exception` one.

**Comment by wookie184** [comment]
> @wookie184 What do you think of creating a global `TASKS` inside the `scheduling` module and save those tasks there ? We would of course add a callback to clear it from the set once done along with the `_log_task_exception` one.

Sounds good (although I'd probably call it `_background_tasks`, not really constant so wouldn't be all caps)

**Comment by shtlrs** [comment]
Okay, the change seems quite easy, shall I take care of this ?

**Comment by wookie184** [comment]
> Okay, the change seems quite easy, shall I take care of this ?

Sure
