### ISSUE TITLE
get_or_fetch_member can raise discord.errors.HTTPException

### ISSUE THREAD

**Issue by mbaruh** [python-discord/bot-core#152]
https://github.com/python-discord/bot-core/blob/6ae78684ee0e61d8a6ad8bb779ea30f2e5294d0d/botcore/utils/members.py#L22-L26

This can raise discord.errors.HTTPException for an invalid user ID (for example a snowflake too far into the future). This should be handled as the user not being found instead.

I'm 99% sure I can make this error in prod (without int e), but would rather save a Sentry alert.

**Comment by ChrisLovering** [comment]
Can `discord.errors.HTTPException` be raised for any other reason? I wouldn't want bot-core to gobble the error if the client should be handling a reason for raising that error themselves.

**Comment by mbaruh** [comment]
I think it will raise it for pretty much any invalid ID

**Comment by mbaruh** [comment]
We could make it's a 40X error and raise otherwise

**Comment by ChrisLovering** [comment]
Sounds like it's fine to change this accept to `HTTPException` then, since `NotFound` is a sub-class.

**Comment by ChrisLovering** [comment]
> > We could make sure it's a 40X error and raise otherwise
> 
> I think we shouldn't obfuscate other 4xx status code, we could indeed make it catch `HTTPException`, and if it's a 400 or 404, we return None, otherwise we raise.
> 
> And I can take this if you want

Sounds good, assigned!
